function xdot = dynamics_asteroidmining(t,in2,in3)
%DYNAMICS_ASTEROIDMINING
%    XDOT = DYNAMICS_ASTEROIDMINING(T,IN2,IN3)

%    This function was generated by the Symbolic Math Toolbox version 24.2.
%    26-Jun-2025 14:46:47

r1 = in2(1,:);
r2 = in2(2,:);
thrust_accel1 = in3(1,:);
thrust_accel2 = in3(2,:);
v1 = in2(3,:);
v2 = in2(4,:);
t2 = r1.^2;
t3 = r2.^2;
t4 = t2+t3;
t5 = 1.0./t4.^(3.0./2.0);
xdot = [v1;v2;thrust_accel1-r1.*t5;thrust_accel2-r2.*t5];
end