function xdot = dynamics(t,in2,in3,in4)
%DYNAMICS
%    XDOT = DYNAMICS(T,IN2,IN3,IN4)

%    This function was generated by the Symbolic Math Toolbox version 24.2.
%    16-Jul-2025 21:41:06

m1 = in2(7,:);
r1 = in2(1,:);
r2 = in2(2,:);
r3 = in2(3,:);
thrust_accel1 = in3(1,:);
thrust_accel2 = in3(2,:);
thrust_accel3 = in3(3,:);
v1 = in2(4,:);
v2 = in2(5,:);
v3 = in2(6,:);
t2 = r1.^2;
t3 = r2.^2;
t4 = r3.^2;
t5 = t2+t3+t4;
t6 = 1.0./t5.^(3.0./2.0);
xdot = [v1;v2;v3;thrust_accel1-r1.*t6;thrust_accel2-r2.*t6;thrust_accel3-r3.*t6;-m1.*sqrt(thrust_accel1.^2+thrust_accel2.^2+thrust_accel3.^2)];
end
