
/*
Auto-generated by CVXPYgen on January 28, 2026 at 02:22:31.
Content: Function definitions.
*/

#include "cpg_solve.h"
#include "cpg_workspace.h"

static cpg_int i;
static cpg_int j;

// Update user-defined parameters
void cpg_update_A(cpg_int idx, cpg_float val){
  cpg_params_vec[idx+0] = val;
  Canon_Outdated.G = 1;
}

void cpg_update_y(cpg_int idx, cpg_float val){
  cpg_params_vec[idx+1384] = val;
  Canon_Outdated.h = 1;
}

// Map user-defined to canonical parameters
void cpg_canonicalize_G(){
  for(i=0; i<1560; i++){
    Canon_Params.G->x[i] = 0;
    for(j=canon_G_map.p[i]; j<canon_G_map.p[i+1]; j++){
      Canon_Params.G->x[i] += canon_G_map.x[j]*cpg_params_vec[canon_G_map.i[j]];
    }
  }
}

void cpg_canonicalize_h(){
  for(i=0; i<184; i++){
    Canon_Params.h[i] = 0;
    for(j=canon_h_map.p[i]; j<canon_h_map.p[i+1]; j++){
      Canon_Params.h[i] += canon_h_map.x[j]*cpg_params_vec[canon_h_map.i[j]];
    }
  }
}

// Retrieve primal solution in terms of user-defined variables
void cpg_retrieve_prim(){
  CPG_Prim.x[0] = qoco_solver->sol->x[1];
  CPG_Prim.x[1] = qoco_solver->sol->x[2];
  CPG_Prim.x[2] = qoco_solver->sol->x[3];
  CPG_Prim.x[3] = qoco_solver->sol->x[4];
  CPG_Prim.x[4] = qoco_solver->sol->x[5];
  CPG_Prim.x[5] = qoco_solver->sol->x[6];
  CPG_Prim.x[6] = qoco_solver->sol->x[7];
  CPG_Prim.x[7] = qoco_solver->sol->x[8];
  CPG_Prim.x[8] = qoco_solver->sol->x[9];
  CPG_Prim.x[9] = qoco_solver->sol->x[10];
  CPG_Prim.x[10] = qoco_solver->sol->x[11];
  CPG_Prim.x[11] = qoco_solver->sol->x[12];
  CPG_Prim.x[12] = qoco_solver->sol->x[13];
  CPG_Prim.x[13] = qoco_solver->sol->x[14];
  CPG_Prim.x[14] = qoco_solver->sol->x[15];
  CPG_Prim.x[15] = qoco_solver->sol->x[16];
  CPG_Prim.x[16] = qoco_solver->sol->x[17];
  CPG_Prim.x[17] = qoco_solver->sol->x[18];
  CPG_Prim.x[18] = qoco_solver->sol->x[19];
  CPG_Prim.x[19] = qoco_solver->sol->x[20];
  CPG_Prim.x[20] = qoco_solver->sol->x[21];
  CPG_Prim.x[21] = qoco_solver->sol->x[22];
  CPG_Prim.x[22] = qoco_solver->sol->x[23];
  CPG_Prim.x[23] = qoco_solver->sol->x[24];
  CPG_Prim.x[24] = qoco_solver->sol->x[25];
  CPG_Prim.x[25] = qoco_solver->sol->x[26];
  CPG_Prim.x[26] = qoco_solver->sol->x[27];
  CPG_Prim.x[27] = qoco_solver->sol->x[28];
  CPG_Prim.x[28] = qoco_solver->sol->x[29];
  CPG_Prim.x[29] = qoco_solver->sol->x[30];
  CPG_Prim.x[30] = qoco_solver->sol->x[31];
  CPG_Prim.x[31] = qoco_solver->sol->x[32];
  CPG_Prim.x[32] = qoco_solver->sol->x[33];
  CPG_Prim.x[33] = qoco_solver->sol->x[34];
  CPG_Prim.x[34] = qoco_solver->sol->x[35];
  CPG_Prim.x[35] = qoco_solver->sol->x[36];
  CPG_Prim.x[36] = qoco_solver->sol->x[37];
  CPG_Prim.x[37] = qoco_solver->sol->x[38];
  CPG_Prim.x[38] = qoco_solver->sol->x[39];
  CPG_Prim.x[39] = qoco_solver->sol->x[40];
  CPG_Prim.x[40] = qoco_solver->sol->x[41];
  CPG_Prim.x[41] = qoco_solver->sol->x[42];
  CPG_Prim.x[42] = qoco_solver->sol->x[43];
  CPG_Prim.x[43] = qoco_solver->sol->x[44];
  CPG_Prim.x[44] = qoco_solver->sol->x[45];
  CPG_Prim.x[45] = qoco_solver->sol->x[46];
  CPG_Prim.x[46] = qoco_solver->sol->x[47];
  CPG_Prim.x[47] = qoco_solver->sol->x[48];
  CPG_Prim.x[48] = qoco_solver->sol->x[49];
  CPG_Prim.x[49] = qoco_solver->sol->x[50];
  CPG_Prim.x[50] = qoco_solver->sol->x[51];
  CPG_Prim.x[51] = qoco_solver->sol->x[52];
  CPG_Prim.x[52] = qoco_solver->sol->x[53];
  CPG_Prim.x[53] = qoco_solver->sol->x[54];
  CPG_Prim.x[54] = qoco_solver->sol->x[55];
  CPG_Prim.x[55] = qoco_solver->sol->x[56];
  CPG_Prim.x[56] = qoco_solver->sol->x[57];
  CPG_Prim.x[57] = qoco_solver->sol->x[58];
  CPG_Prim.x[58] = qoco_solver->sol->x[59];
  CPG_Prim.x[59] = qoco_solver->sol->x[60];
  CPG_Prim.x[60] = qoco_solver->sol->x[61];
  CPG_Prim.x[61] = qoco_solver->sol->x[62];
  CPG_Prim.x[62] = qoco_solver->sol->x[63];
  CPG_Prim.x[63] = qoco_solver->sol->x[64];
  CPG_Prim.x[64] = qoco_solver->sol->x[65];
  CPG_Prim.x[65] = qoco_solver->sol->x[66];
  CPG_Prim.x[66] = qoco_solver->sol->x[67];
  CPG_Prim.x[67] = qoco_solver->sol->x[68];
  CPG_Prim.x[68] = qoco_solver->sol->x[69];
  CPG_Prim.x[69] = qoco_solver->sol->x[70];
  CPG_Prim.x[70] = qoco_solver->sol->x[71];
  CPG_Prim.x[71] = qoco_solver->sol->x[72];
  CPG_Prim.x[72] = qoco_solver->sol->x[73];
  CPG_Prim.x[73] = qoco_solver->sol->x[74];
  CPG_Prim.x[74] = qoco_solver->sol->x[75];
  CPG_Prim.x[75] = qoco_solver->sol->x[76];
  CPG_Prim.x[76] = qoco_solver->sol->x[77];
  CPG_Prim.x[77] = qoco_solver->sol->x[78];
  CPG_Prim.x[78] = qoco_solver->sol->x[79];
  CPG_Prim.x[79] = qoco_solver->sol->x[80];
  CPG_Prim.x[80] = qoco_solver->sol->x[81];
  CPG_Prim.x[81] = qoco_solver->sol->x[82];
  CPG_Prim.x[82] = qoco_solver->sol->x[83];
  CPG_Prim.x[83] = qoco_solver->sol->x[84];
  CPG_Prim.x[84] = qoco_solver->sol->x[85];
  CPG_Prim.x[85] = qoco_solver->sol->x[86];
  CPG_Prim.x[86] = qoco_solver->sol->x[87];
  CPG_Prim.x[87] = qoco_solver->sol->x[88];
  CPG_Prim.x[88] = qoco_solver->sol->x[89];
  CPG_Prim.x[89] = qoco_solver->sol->x[90];
  CPG_Prim.x[90] = qoco_solver->sol->x[91];
  CPG_Prim.x[91] = qoco_solver->sol->x[92];
  CPG_Prim.x[92] = qoco_solver->sol->x[93];
  CPG_Prim.x[93] = qoco_solver->sol->x[94];
  CPG_Prim.x[94] = qoco_solver->sol->x[95];
  CPG_Prim.x[95] = qoco_solver->sol->x[96];
  CPG_Prim.x[96] = qoco_solver->sol->x[97];
  CPG_Prim.x[97] = qoco_solver->sol->x[98];
  CPG_Prim.x[98] = qoco_solver->sol->x[99];
  CPG_Prim.x[99] = qoco_solver->sol->x[100];
  CPG_Prim.x[100] = qoco_solver->sol->x[101];
  CPG_Prim.x[101] = qoco_solver->sol->x[102];
  CPG_Prim.x[102] = qoco_solver->sol->x[103];
  CPG_Prim.x[103] = qoco_solver->sol->x[104];
  CPG_Prim.x[104] = qoco_solver->sol->x[105];
  CPG_Prim.x[105] = qoco_solver->sol->x[106];
  CPG_Prim.x[106] = qoco_solver->sol->x[107];
  CPG_Prim.x[107] = qoco_solver->sol->x[108];
  CPG_Prim.x[108] = qoco_solver->sol->x[109];
  CPG_Prim.x[109] = qoco_solver->sol->x[110];
  CPG_Prim.x[110] = qoco_solver->sol->x[111];
  CPG_Prim.x[111] = qoco_solver->sol->x[112];
  CPG_Prim.x[112] = qoco_solver->sol->x[113];
  CPG_Prim.x[113] = qoco_solver->sol->x[114];
  CPG_Prim.x[114] = qoco_solver->sol->x[115];
  CPG_Prim.x[115] = qoco_solver->sol->x[116];
  CPG_Prim.x[116] = qoco_solver->sol->x[117];
  CPG_Prim.x[117] = qoco_solver->sol->x[118];
  CPG_Prim.x[118] = qoco_solver->sol->x[119];
  CPG_Prim.x[119] = qoco_solver->sol->x[120];
  CPG_Prim.x[120] = qoco_solver->sol->x[121];
  CPG_Prim.x[121] = qoco_solver->sol->x[122];
  CPG_Prim.x[122] = qoco_solver->sol->x[123];
  CPG_Prim.x[123] = qoco_solver->sol->x[124];
  CPG_Prim.x[124] = qoco_solver->sol->x[125];
  CPG_Prim.x[125] = qoco_solver->sol->x[126];
  CPG_Prim.x[126] = qoco_solver->sol->x[127];
  CPG_Prim.x[127] = qoco_solver->sol->x[128];
  CPG_Prim.x[128] = qoco_solver->sol->x[129];
  CPG_Prim.x[129] = qoco_solver->sol->x[130];
  CPG_Prim.x[130] = qoco_solver->sol->x[131];
  CPG_Prim.x[131] = qoco_solver->sol->x[132];
  CPG_Prim.x[132] = qoco_solver->sol->x[133];
  CPG_Prim.x[133] = qoco_solver->sol->x[134];
  CPG_Prim.x[134] = qoco_solver->sol->x[135];
  CPG_Prim.x[135] = qoco_solver->sol->x[136];
  CPG_Prim.x[136] = qoco_solver->sol->x[137];
  CPG_Prim.x[137] = qoco_solver->sol->x[138];
  CPG_Prim.x[138] = qoco_solver->sol->x[139];
  CPG_Prim.x[139] = qoco_solver->sol->x[140];
  CPG_Prim.x[140] = qoco_solver->sol->x[141];
  CPG_Prim.x[141] = qoco_solver->sol->x[142];
  CPG_Prim.x[142] = qoco_solver->sol->x[143];
  CPG_Prim.x[143] = qoco_solver->sol->x[144];
  CPG_Prim.x[144] = qoco_solver->sol->x[145];
  CPG_Prim.x[145] = qoco_solver->sol->x[146];
  CPG_Prim.x[146] = qoco_solver->sol->x[147];
  CPG_Prim.x[147] = qoco_solver->sol->x[148];
  CPG_Prim.x[148] = qoco_solver->sol->x[149];
  CPG_Prim.x[149] = qoco_solver->sol->x[150];
  CPG_Prim.x[150] = qoco_solver->sol->x[151];
  CPG_Prim.x[151] = qoco_solver->sol->x[152];
  CPG_Prim.x[152] = qoco_solver->sol->x[153];
  CPG_Prim.x[153] = qoco_solver->sol->x[154];
  CPG_Prim.x[154] = qoco_solver->sol->x[155];
  CPG_Prim.x[155] = qoco_solver->sol->x[156];
  CPG_Prim.x[156] = qoco_solver->sol->x[157];
  CPG_Prim.x[157] = qoco_solver->sol->x[158];
  CPG_Prim.x[158] = qoco_solver->sol->x[159];
  CPG_Prim.x[159] = qoco_solver->sol->x[160];
  CPG_Prim.x[160] = qoco_solver->sol->x[161];
  CPG_Prim.x[161] = qoco_solver->sol->x[162];
  CPG_Prim.x[162] = qoco_solver->sol->x[163];
  CPG_Prim.x[163] = qoco_solver->sol->x[164];
  CPG_Prim.x[164] = qoco_solver->sol->x[165];
  CPG_Prim.x[165] = qoco_solver->sol->x[166];
  CPG_Prim.x[166] = qoco_solver->sol->x[167];
  CPG_Prim.x[167] = qoco_solver->sol->x[168];
  CPG_Prim.x[168] = qoco_solver->sol->x[169];
  CPG_Prim.x[169] = qoco_solver->sol->x[170];
  CPG_Prim.x[170] = qoco_solver->sol->x[171];
  CPG_Prim.x[171] = qoco_solver->sol->x[172];
  CPG_Prim.x[172] = qoco_solver->sol->x[173];
}

// Retrieve dual solution in terms of user-defined constraints
void cpg_retrieve_dual(){
  CPG_Dual.d0 = qoco_solver->sol->z[0];
}

// Retrieve solver info
void cpg_retrieve_info(){
  CPG_Info.obj_val = (qoco_solver->sol->obj);
  CPG_Info.iter = qoco_solver->sol->iters;
  CPG_Info.status = qoco_solver->sol->status;
  CPG_Info.pri_res = qoco_solver->sol->pres;
  CPG_Info.dua_res = qoco_solver->sol->dres;
}

// Copy canonical parameters for preconditioning
void cpg_copy_c(){
  for (i=0; i<175; i++){
    Canon_Params_conditioning.c[i] = Canon_Params.c[i];
  }
}

void cpg_copy_A(){
}

void cpg_copy_b(){
}

void cpg_copy_G(){
  for (i=0; i<1560; i++){
    Canon_Params_conditioning.G->x[i] = Canon_Params.G->x[i];
  }
}

void cpg_copy_h(){
  for (i=0; i<184; i++){
    Canon_Params_conditioning.h[i] = Canon_Params.h[i];
  }
}

void cpg_copy_all(){
  cpg_copy_c();
  cpg_copy_A();
  cpg_copy_b();
  cpg_copy_G();
  cpg_copy_h();
}

// Solve via canonicalization, canonical solve, retrieval
void cpg_solve(){
  // Canonicalize if necessary
  if (Canon_Outdated.G) {
    cpg_canonicalize_G();
  }
  if (Canon_Outdated.h) {
    cpg_canonicalize_h();
  }
  if (!qoco_solver ) {
    cpg_copy_all();
   QOCOCscMatrix* P = (QOCOCscMatrix*)malloc(sizeof(QOCOCscMatrix));
   QOCOCscMatrix* A = (QOCOCscMatrix*)malloc(sizeof(QOCOCscMatrix));
   QOCOCscMatrix* G = (QOCOCscMatrix*)malloc(sizeof(QOCOCscMatrix));
   P = NULL;
   A = NULL;
   qoco_set_csc(G, 184, 175, Canon_Params.G->nnz, Canon_Params.G->x, Canon_Params.G->p, Canon_Params.G->i);
   QOCOSettings* qoco_settings = (QOCOSettings*)malloc(sizeof(QOCOSettings));
   set_default_settings(qoco_settings);
   qoco_solver = (QOCOSolver*)malloc(sizeof(QOCOSolver));
   qoco_setup(qoco_solver, 175, 184, 0, P, Canon_Params.c, A, NULL, G, Canon_Params.h, 1, 2, (int *) &qoco_q, qoco_settings);
  }
  if (Canon_Outdated.h) {
    update_vector_data(qoco_solver, NULL, NULL, Canon_Params.h);
  }
  if (Canon_Outdated.G) {
    update_matrix_data(qoco_solver, NULL, NULL, Canon_Params.G->x);
  }
  qoco_solver->settings->max_iters = Canon_Settings.max_iters;
  qoco_solver->settings->bisect_iters = Canon_Settings.bisect_iters;
  qoco_solver->settings->ruiz_iters = Canon_Settings.ruiz_iters;
  qoco_solver->settings->iter_ref_iters = Canon_Settings.iter_ref_iters;
  qoco_solver->settings->kkt_static_reg = Canon_Settings.kkt_static_reg;
  qoco_solver->settings->kkt_dynamic_reg = Canon_Settings.kkt_dynamic_reg;
  qoco_solver->settings->abstol = Canon_Settings.abstol;
  qoco_solver->settings->reltol = Canon_Settings.reltol;
  qoco_solver->settings->abstol_inacc = Canon_Settings.abstol_inacc;
  qoco_solver->settings->reltol_inacc = Canon_Settings.reltol_inacc;
  qoco_solver->settings->verbose = Canon_Settings.verbose;
  // Solve with QOCO
  qoco_solve(qoco_solver);
  // Retrieve results
  cpg_retrieve_prim();
  cpg_retrieve_dual();
  cpg_retrieve_info();
  // Reset flags for outdated canonical parameters
  Canon_Outdated.G = 0;
  Canon_Outdated.h = 0;
}

// Update solver settings
void cpg_set_solver_default_settings(){
  Canon_Settings.max_iters = 200;
  Canon_Settings.bisect_iters = 5;
  Canon_Settings.ruiz_iters = 0;
  Canon_Settings.iter_ref_iters = 1;
  Canon_Settings.kkt_static_reg = 1e-8;
  Canon_Settings.kkt_dynamic_reg = 1e-8;
  Canon_Settings.abstol = 1e-7;
  Canon_Settings.reltol = 1e-7;
  Canon_Settings.abstol_inacc = 1e-5;
  Canon_Settings.reltol_inacc = 1e-5;
  Canon_Settings.verbose = 0;
}

void cpg_set_solver_max_iters(cpg_int max_iters_new){
  Canon_Settings.max_iters = max_iters_new;
}

void cpg_set_solver_bisect_iters(cpg_int bisect_iters_new){
  Canon_Settings.bisect_iters = bisect_iters_new;
}

void cpg_set_solver_ruiz_iters(cpg_int ruiz_iters_new){
  Canon_Settings.ruiz_iters = ruiz_iters_new;
}

void cpg_set_solver_iter_ref_iters(cpg_int iter_ref_iters_new){
  Canon_Settings.iter_ref_iters = iter_ref_iters_new;
}

void cpg_set_solver_kkt_static_reg(cpg_float kkt_static_reg_new){
  Canon_Settings.kkt_static_reg = kkt_static_reg_new;
}

void cpg_set_solver_kkt_dynamic_reg(cpg_float kkt_dynamic_reg_new){
  Canon_Settings.kkt_dynamic_reg = kkt_dynamic_reg_new;
}

void cpg_set_solver_abstol(cpg_float abstol_new){
  Canon_Settings.abstol = abstol_new;
}

void cpg_set_solver_reltol(cpg_float reltol_new){
  Canon_Settings.reltol = reltol_new;
}

void cpg_set_solver_abstol_inacc(cpg_float abstol_inacc_new){
  Canon_Settings.abstol_inacc = abstol_inacc_new;
}

void cpg_set_solver_reltol_inacc(cpg_float reltol_inacc_new){
  Canon_Settings.reltol_inacc = reltol_inacc_new;
}

void cpg_set_solver_verbose(cpg_int verbose_new){
  Canon_Settings.verbose = verbose_new;
}
