
/*
Auto-generated by CVXPYgen on October 25, 2025 at 16:16:47.
Content: Function definitions.
*/

#include "cpg_solve.h"
#include "cpg_workspace.h"

static cpg_int i;
static cpg_int j;

// Update user-defined parameters
void cpg_update_y(cpg_int idx, cpg_float val){
  cpg_params_vec[idx+0] = val;
  Canon_Outdated.h = 1;
}

// Map user-defined to canonical parameters
void cpg_canonicalize_h(){
  for(i=0; i<7; i++){
    Canon_Params.h[i] = 0;
    for(j=canon_h_map.p[i]; j<canon_h_map.p[i+1]; j++){
      Canon_Params.h[i] += canon_h_map.x[j]*cpg_params_vec[canon_h_map.i[j]];
    }
  }
}

// Retrieve primal solution in terms of user-defined variables
void cpg_retrieve_prim(){
  CPG_Prim.x[0] = qoco_solver->sol->x[1];
  CPG_Prim.x[1] = qoco_solver->sol->x[2];
}

// Retrieve dual solution in terms of user-defined constraints
void cpg_retrieve_dual(){
  CPG_Dual.d0 = qoco_solver->sol->z[0];
}

// Retrieve solver info
void cpg_retrieve_info(){
  CPG_Info.obj_val = (qoco_solver->sol->obj);
  CPG_Info.iter = qoco_solver->sol->iters;
  CPG_Info.status = qoco_solver->sol->status;
  CPG_Info.pri_res = qoco_solver->sol->pres;
  CPG_Info.dua_res = qoco_solver->sol->dres;
}

// Copy canonical parameters for preconditioning
void cpg_copy_c(){
  for (i=0; i<4; i++){
    Canon_Params_conditioning.c[i] = Canon_Params.c[i];
  }
}

void cpg_copy_A(){
}

void cpg_copy_b(){
}

void cpg_copy_G(){
  for (i=0; i<9; i++){
    Canon_Params_conditioning.G->x[i] = Canon_Params.G->x[i];
  }
}

void cpg_copy_h(){
  for (i=0; i<7; i++){
    Canon_Params_conditioning.h[i] = Canon_Params.h[i];
  }
}

void cpg_copy_all(){
  cpg_copy_c();
  cpg_copy_A();
  cpg_copy_b();
  cpg_copy_G();
  cpg_copy_h();
}

// Solve via canonicalization, canonical solve, retrieval
void cpg_solve(){
  // Canonicalize if necessary
  if (Canon_Outdated.h) {
    cpg_canonicalize_h();
  }
  if (!qoco_solver ) {
    cpg_copy_all();
   QOCOCscMatrix* P = (QOCOCscMatrix*)malloc(sizeof(QOCOCscMatrix));
   QOCOCscMatrix* A = (QOCOCscMatrix*)malloc(sizeof(QOCOCscMatrix));
   QOCOCscMatrix* G = (QOCOCscMatrix*)malloc(sizeof(QOCOCscMatrix));
   P = NULL;
   A = NULL;
   qoco_set_csc(G, 7, 4, Canon_Params.G->nnz, Canon_Params.G->x, Canon_Params.G->p, Canon_Params.G->i);
   QOCOSettings* qoco_settings = (QOCOSettings*)malloc(sizeof(QOCOSettings));
   set_default_settings(qoco_settings);
   qoco_solver = (QOCOSolver*)malloc(sizeof(QOCOSolver));
   qoco_setup(qoco_solver, 4, 7, 0, P, Canon_Params.c, A, NULL, G, Canon_Params.h, 1, 2, (int *) &qoco_q, qoco_settings);
  }
  if (Canon_Outdated.h) {
    update_vector_data(qoco_solver, NULL, NULL, Canon_Params.h);
  }
  qoco_solver->settings->max_iters = Canon_Settings.max_iters;
  qoco_solver->settings->bisect_iters = Canon_Settings.bisect_iters;
  qoco_solver->settings->ruiz_iters = Canon_Settings.ruiz_iters;
  qoco_solver->settings->iter_ref_iters = Canon_Settings.iter_ref_iters;
  qoco_solver->settings->kkt_static_reg = Canon_Settings.kkt_static_reg;
  qoco_solver->settings->kkt_dynamic_reg = Canon_Settings.kkt_dynamic_reg;
  qoco_solver->settings->abstol = Canon_Settings.abstol;
  qoco_solver->settings->reltol = Canon_Settings.reltol;
  qoco_solver->settings->abstol_inacc = Canon_Settings.abstol_inacc;
  qoco_solver->settings->reltol_inacc = Canon_Settings.reltol_inacc;
  qoco_solver->settings->verbose = Canon_Settings.verbose;
  // Solve with QOCO
  qoco_solve(qoco_solver);
  // Retrieve results
  cpg_retrieve_prim();
  cpg_retrieve_dual();
  cpg_retrieve_info();
  // Reset flags for outdated canonical parameters
  Canon_Outdated.h = 0;
}

// Update solver settings
void cpg_set_solver_default_settings(){
  Canon_Settings.max_iters = 200;
  Canon_Settings.bisect_iters = 5;
  Canon_Settings.ruiz_iters = 0;
  Canon_Settings.iter_ref_iters = 1;
  Canon_Settings.kkt_static_reg = 1e-8;
  Canon_Settings.kkt_dynamic_reg = 1e-8;
  Canon_Settings.abstol = 1e-7;
  Canon_Settings.reltol = 1e-7;
  Canon_Settings.abstol_inacc = 1e-5;
  Canon_Settings.reltol_inacc = 1e-5;
  Canon_Settings.verbose = 0;
}

void cpg_set_solver_max_iters(cpg_int max_iters_new){
  Canon_Settings.max_iters = max_iters_new;
}

void cpg_set_solver_bisect_iters(cpg_int bisect_iters_new){
  Canon_Settings.bisect_iters = bisect_iters_new;
}

void cpg_set_solver_ruiz_iters(cpg_int ruiz_iters_new){
  Canon_Settings.ruiz_iters = ruiz_iters_new;
}

void cpg_set_solver_iter_ref_iters(cpg_int iter_ref_iters_new){
  Canon_Settings.iter_ref_iters = iter_ref_iters_new;
}

void cpg_set_solver_kkt_static_reg(cpg_float kkt_static_reg_new){
  Canon_Settings.kkt_static_reg = kkt_static_reg_new;
}

void cpg_set_solver_kkt_dynamic_reg(cpg_float kkt_dynamic_reg_new){
  Canon_Settings.kkt_dynamic_reg = kkt_dynamic_reg_new;
}

void cpg_set_solver_abstol(cpg_float abstol_new){
  Canon_Settings.abstol = abstol_new;
}

void cpg_set_solver_reltol(cpg_float reltol_new){
  Canon_Settings.reltol = reltol_new;
}

void cpg_set_solver_abstol_inacc(cpg_float abstol_inacc_new){
  Canon_Settings.abstol_inacc = abstol_inacc_new;
}

void cpg_set_solver_reltol_inacc(cpg_float reltol_inacc_new){
  Canon_Settings.reltol_inacc = reltol_inacc_new;
}

void cpg_set_solver_verbose(cpg_int verbose_new){
  Canon_Settings.verbose = verbose_new;
}
