
/*
Auto-generated by CVXPYgen on October 25, 2025 at 16:16:47.
Content: Example program for updating parameters, solving, and inspecting the result.
*/

#include <stdio.h>
#include "cpg_workspace.h"
#include "cpg_solve.h"

static int i;

int main(int argc, char *argv[]){

  // Update first entry of every user-defined parameter
  cpg_update_y(0, 1.00000000000000000000);

  // Solve the problem instance
  cpg_solve();

  // Print objective function value
  printf("obj = %f\n", CPG_Result.info->obj_val);

  // Print primal solution
  for(i=0; i<2; i++) {
    printf("x[%d] = %f\n", i, CPG_Result.prim->x[i]);
  }

  // Print dual solution
  printf("d0 = %f\n", CPG_Result.dual->d0);

  return 0;

}
