
/*
Auto-generated by CVXPYgen on October 25, 2025 at 16:16:47.
Content: Variable definitions.
*/

#include "cpg_workspace.h"

// Vector containing flattened user-defined parameters
cpg_float cpg_params_vec[3] = {
(cpg_float)1.00000000000000000000,
(cpg_float)2.00000000000000000000,
(cpg_float)1.00000000000000000000,
};

// Sparse mappings from user-defined to canonical parameters
cpg_int canon_h_map_i[3] = {
2,
0,
1,
};
cpg_int canon_h_map_p[8] = {
0,
1,
1,
1,
1,
1,
2,
3,
};
cpg_float canon_h_map_x[3] = {
(cpg_float)0.10000000000000000555,
(cpg_float)-1.00000000000000000000,
(cpg_float)-1.00000000000000000000,
};
cpg_csc canon_h_map = {canon_h_map_p, canon_h_map_i, canon_h_map_x, 3};

// Canonical parameters
cpg_float canon_c[4] = {
(cpg_float)1.00000000000000000000,
(cpg_float)0.00000000000000000000,
(cpg_float)0.00000000000000000000,
(cpg_float)0.00000000000000000000,
};

cpg_float canon_c_conditioning[4] = {
(cpg_float)1.00000000000000000000,
(cpg_float)0.00000000000000000000,
(cpg_float)0.00000000000000000000,
(cpg_float)0.00000000000000000000,
};

cpg_int canon_G_i[9] = {
1,
2,
5,
6,
3,
5,
6,
0,
4,
};
cpg_int canon_G_p[5] = {
0,
1,
4,
7,
9,
};
cpg_float canon_G_x[9] = {
(cpg_float)-1.00000000000000000000,
(cpg_float)-1.00000000000000000000,
(cpg_float)5.00000000000000000000,
(cpg_float)-8.00000000000000000000,
(cpg_float)-1.00000000000000000000,
(cpg_float)11.00000000000000000000,
(cpg_float)-2.00000000000000000000,
(cpg_float)1.00000000000000000000,
(cpg_float)-1.00000000000000000000,
};
cpg_csc canon_G = {canon_G_p, canon_G_i, canon_G_x, 9};

cpg_int canon_G_conditioning_i[9] = {
1,
2,
5,
6,
3,
5,
6,
0,
4,
};
cpg_int canon_G_conditioning_p[5] = {
0,
1,
4,
7,
9,
};
cpg_float canon_G_conditioning_x[9] = {
(cpg_float)-1.00000000000000000000,
(cpg_float)-1.00000000000000000000,
(cpg_float)5.00000000000000000000,
(cpg_float)-8.00000000000000000000,
(cpg_float)-1.00000000000000000000,
(cpg_float)11.00000000000000000000,
(cpg_float)-2.00000000000000000000,
(cpg_float)1.00000000000000000000,
(cpg_float)-1.00000000000000000000,
};
cpg_csc canon_G_conditioning = {canon_G_conditioning_p, canon_G_conditioning_i, canon_G_conditioning_x, 9};

cpg_float canon_h[7] = {
(cpg_float)0.10000000000000000555,
(cpg_float)0.00000000000000000000,
(cpg_float)0.00000000000000000000,
(cpg_float)0.00000000000000000000,
(cpg_float)0.00000000000000000000,
(cpg_float)-1.00000000000000000000,
(cpg_float)-2.00000000000000000000,
};

cpg_float canon_h_conditioning[7] = {
(cpg_float)0.10000000000000000555,
(cpg_float)0.00000000000000000000,
(cpg_float)0.00000000000000000000,
(cpg_float)0.00000000000000000000,
(cpg_float)0.00000000000000000000,
(cpg_float)-1.00000000000000000000,
(cpg_float)-2.00000000000000000000,
};

// Struct containing canonical parameters
Canon_Params_t Canon_Params = {
.c = (cpg_float *) &canon_c,
.d = 0.00000000000000000000,
.A = 0,
.b = 0,
.G = &canon_G,
.h = (cpg_float *) &canon_h,
};

Canon_Params_t Canon_Params_conditioning = {
.c = (cpg_float *) &canon_c_conditioning,
.d = 0.00000000000000000000,
.A = 0,
.b = 0,
.G = &canon_G_conditioning,
.h = (cpg_float *) &canon_h_conditioning,
};

// Struct containing flags for outdated canonical parameters
Canon_Outdated_t Canon_Outdated = {
.c = 1,
.d = 1,
.A = 1,
.b = 1,
.G = 1,
.h = 1,
};

// User-defined variables
cpg_float x[2] = {
(cpg_float)0.00000000000000000000,
(cpg_float)0.00000000000000000000,
};

// Struct containing primal solution
CPG_Prim_t CPG_Prim = {
.x = (cpg_float *) &x,
};

// Dual variables associated with user-defined constraints
// Struct containing dual solution
CPG_Dual_t CPG_Dual = {
.d0 = 0,
};

// Struct containing solver info
CPG_Info_t CPG_Info = {
.obj_val = 0,
.iter = 0,
.status = 0,
.pri_res = 0,
.dua_res = 0,
};

// Struct containing solution and info
CPG_Result_t CPG_Result = {
.prim = &CPG_Prim,
.dual = &CPG_Dual,
.info = &CPG_Info,
};

// Struct containing solver settings
Canon_Settings_t Canon_Settings = {
.max_iters = 200,
.bisect_iters = 5,
.ruiz_iters = 0,
.iter_ref_iters = 1,
.kkt_static_reg = 1e-8,
.kkt_dynamic_reg = 1e-8,
.abstol = 1e-7,
.reltol = 1e-7,
.abstol_inacc = 1e-5,
.reltol_inacc = 1e-5,
.verbose = 0,
};

// QOCO array of SOC dimensions
cpg_int qoco_q[2] = {
3,
3,
};

// QOCO solver
QOCOSolver* qoco_solver = NULL;

// QOCO exit flag
cpg_int qoco_flag = -99;
