function xdot = dynamics(t,in2,in3,in4)
%DYNAMICS
%    XDOT = DYNAMICS(T,IN2,IN3,IN4)

%    This function was generated by the Symbolic Math Toolbox version 24.2.
%    16-Jul-2025 23:21:22

m1 = in2(7,:);
r1 = in2(1,:);
r2 = in2(2,:);
r3 = in2(3,:);
thrust_accel1 = in3(1,:);
thrust_accel2 = in3(2,:);
thrust_accel3 = in3(3,:);
v1 = in2(4,:);
v2 = in2(5,:);
v3 = in2(6,:);
t2 = r1.^2;
t3 = r2.^2;
t4 = r3.^2;
t5 = 1.0./m1;
t6 = t2+t3+t4;
t7 = 1.0./t6.^(3.0./2.0);
xdot = [v1;v2;v3;-r1.*t7+t5.*thrust_accel1;-r2.*t7+t5.*thrust_accel2;-r3.*t7+t5.*thrust_accel3;sqrt(thrust_accel1.^2+thrust_accel2.^2+thrust_accel3.^2).*(-1.0./2.0)];
end
